// Mock roadmap data for PaperSwipe AI Bot. Replace with real LLM output later.
window.__PAPERSWIPE_ROADMAP__ = {
  title: "LLM Agent Long-Term Memory · Learning Roadmap",
  subtitle: "Build a foundation with surveys, harden the theory with classics, then track the latest frontier",
  stages: [
    {
      id: "survey",
      tag: "Survey",
      title: "Foundation · Survey the landscape",
      hint: "Build the big picture first — subproblems, main lineages, and evaluation conventions",
      accent: "violet",
      icon: "book-open-text",
      papers: [
        {
          title: "A Survey on Memory Mechanisms of LLM Agents",
          authors: "Zhang et al.",
          year: 2024,
          venue: "arXiv preprint",
          minutes: 45,
          tldr: "A systematic map of short- and long-term memory categories, retrieval, and update strategies in LLM agents.",
        },
        {
          title: "Retrieval-Augmented Generation: A Survey",
          authors: "Gao et al.",
          year: 2024,
          venue: "ACM Comput. Surv.",
          minutes: 38,
          tldr: "Covers RAG's core components, benchmarks, and open-source frameworks — a natural lead-in to memory retrieval.",
        },
      ],
    },
    {
      id: "classic",
      tag: "Classic",
      title: "Fundamentals · Classic papers",
      hint: "Read the heavily-cited methods to grasp the evaluation frames and common tricks",
      accent: "coral",
      icon: "landmark",
      papers: [
        {
          title: "MemGPT: Towards LLMs as Operating Systems",
          authors: "Packer et al.",
          year: 2023,
          venue: "arXiv",
          minutes: 32,
          tldr: "Treats the context window as tiered memory that can page conversation history in and out on demand.",
        },
        {
          title: "Generative Agents: Interactive Simulacra of Human Behavior",
          authors: "Park et al.",
          year: 2023,
          venue: "UIST",
          minutes: 40,
          tldr: "Proposes the reflect + recall + plan three-stage memory architecture — the prototype for agent memory work.",
        },
        {
          title: "REALM: Retrieval-Augmented Language Model Pretraining",
          authors: "Guu et al.",
          year: 2020,
          venue: "ICML",
          minutes: 28,
          tldr: "End-to-end trainable retrieval-augmented language model — the foundation of the later RAG line of work.",
        },
      ],
    },
    {
      id: "recent",
      tag: "Latest",
      title: "Frontier · Latest advances",
      hint: "Catch up on the last six months of SOTA and pick one or two threads to dig into",
      accent: "teal",
      icon: "sparkles",
      papers: [
        {
          title: "Larimar: LLM-Augmented Episodic Memory",
          authors: "Das et al.",
          year: 2025,
          venue: "ICLR",
          minutes: 30,
          tldr: "Introduces an editable episodic memory module supporting knowledge updates and forgetting.",
        },
        {
          title: "A-Mem: Adaptive Memory for Long-Horizon Agents",
          authors: "Wu et al.",
          year: 2025,
          venue: "NeurIPS",
          minutes: 34,
          tldr: "Adaptively decides when to write, retrieve, and summarize — a large gain on long-horizon tasks.",
        },
        {
          title: "MemoryBank: Reflective Long-Term Memory for LLMs",
          authors: "Liu et al.",
          year: 2024,
          venue: "AAAI",
          minutes: 26,
          tldr: "Inspired by the Ebbinghaus forgetting curve — consolidates and recalls memory by importance.",
        },
      ],
    },
  ],
};
