// Mock roadmap data for PaperSwipe AI Bot. Replace with real LLM output later.
window.__PAPERSWIPE_ROADMAP__ = {
  title: "LLM Agent 长期记忆 · 学习路线图",
  subtitle: "从综述打基础，到经典夯实原理，再到最新前沿追踪",
  stages: [
    {
      id: "survey",
      tag: "综述",
      title: "打地基 · 综述扫盲",
      hint: "先建立整体认知，明确子问题、关键流派、评测口径",
      accent: "violet",
      icon: "book-open-text",
      papers: [
        {
          title: "A Survey on Memory Mechanisms of LLM Agents",
          authors: "Zhang et al.",
          year: 2024,
          venue: "arXiv preprint",
          minutes: 45,
          tldr: "系统梳理 LLM 智能体的短期 / 长期记忆分类、检索与更新策略。",
        },
        {
          title: "Retrieval-Augmented Generation: A Survey",
          authors: "Gao et al.",
          year: 2024,
          venue: "ACM Comput. Surv.",
          minutes: 38,
          tldr: "覆盖 RAG 的核心组件、评测基准与开源框架，可作为记忆检索的先导阅读。",
        },
      ],
    },
    {
      id: "classic",
      tag: "经典",
      title: "夯实原理 · 经典论文",
      hint: "读懂被反复引用的方法，摸清评价框架和常见 trick",
      accent: "coral",
      icon: "landmark",
      papers: [
        {
          title: "MemGPT: Towards LLMs as Operating Systems",
          authors: "Packer et al.",
          year: 2023,
          venue: "arXiv",
          minutes: 32,
          tldr: "把上下文当分层内存管理，可按需换入换出会话历史。",
        },
        {
          title: "Generative Agents: Interactive Simulacra of Human Behavior",
          authors: "Park et al.",
          year: 2023,
          venue: "UIST",
          minutes: 40,
          tldr: "提出反思 + 回忆 + 计划三段式记忆架构，是 agent 记忆的原型工作。",
        },
        {
          title: "REALM: Retrieval-Augmented Language Model Pretraining",
          authors: "Guu et al.",
          year: 2020,
          venue: "ICML",
          minutes: 28,
          tldr: "端到端可训练的检索式语言模型，为后续 RAG 系列奠基。",
        },
      ],
    },
    {
      id: "recent",
      tag: "最新",
      title: "追踪前沿 · 最新进展",
      hint: "跟上最近半年的 SOTA，挑一两条方向深入",
      accent: "teal",
      icon: "sparkles",
      papers: [
        {
          title: "Larimar: LLM-Augmented Episodic Memory",
          authors: "Das et al.",
          year: 2025,
          venue: "ICLR",
          minutes: 30,
          tldr: "引入可编辑的情景记忆模块，支持知识更新与遗忘。",
        },
        {
          title: "A-Mem: Adaptive Memory for Long-Horizon Agents",
          authors: "Wu et al.",
          year: 2025,
          venue: "NeurIPS",
          minutes: 34,
          tldr: "自适应决定何时写入 / 检索 / 摘要，长时任务表现显著提升。",
        },
        {
          title: "MemoryBank: Reflective Long-Term Memory for LLMs",
          authors: "Liu et al.",
          year: 2024,
          venue: "AAAI",
          minutes: 26,
          tldr: "受艾宾浩斯遗忘曲线启发，按重要性做记忆巩固与召回。",
        },
      ],
    },
  ],
};
